[input]
base_directory = "/home/asharma/advanced_cpp_by_example/output"
html_selector = "main"

[[input.files]]
path = "introduction-to-smart-pointers.html"
url = "/introduction-to-smart-pointers.html"
title = "Introduction to smart pointers"

[[input.files]]
path = "templates.html"
url = "/templates.html"
title = "Templates"

[[input.files]]
path = "variadic-templates.html"
url = "/variadic-templates.html"
title = "Variadic Templates"

[[input.files]]
path = "type-traits.html"
url = "/type-traits.html"
title = "Type traits"